steps:
  # Step 1: Install Python dependencies
  - name: 'python:3.10'
    entrypoint: pip
    args: ["install", "-r", "utils/requirements.txt", "--user"]

  # Step 2: Run the upload script
  - name: 'python:3.10'
    entrypoint: python
    args:
      - "utils/add_dags_to_composer.py"
      - "--dags_directory=${_DAGS_DIRECTORY}"
      - "--dags_bucket=${_DAGS_BUCKET}"
      - "--data_directory=${_DATA_DIRECTORY}"

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _DAGS_DIRECTORY: "."  # ✅ DAGs are in root folder
  _DATA_DIRECTORY: "data/"
  _DAGS_BUCKET: "us-central1-gcp-practice-1--b8ac77c1-bucket"
